# Generated by Django 5.0.6 on 2024-05-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0004_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies_app.client'),
        ),
    ]
