# Generated by Django 5.0.6 on 2024-06-11 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0005_company_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1)], verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.TextField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.TextField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500, verbose_name='text'),
        ),
    ]
